"""add_saved_recipes

Revision ID: 48159f7c0618
Revises: cdb8a733ce88
Create Date: 2026-06-09 08:55:34.348699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_saved_recipes

Revision ID: 48159f7c0618
Revises: cdb8a733ce88
Create Date: 2026-06-09 08:55:34.348699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48159f7c0618'
down_revision: Union[str, Sequence[str], None] = 'cdb8a733ce88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('recipe_type', sa.String(), nullable=False),
    sa.Column('recipe_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_recipes_client_id'), 'saved_recipes', ['client_id'], unique=False)
    op.create_index(op.f('ix_saved_recipes_id'), 'saved_recipes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_recipes_id'), table_name='saved_recipes')
    op.drop_index(op.f('ix_saved_recipes_client_id'), table_name='saved_recipes')
    op.drop_table('saved_recipes')
    # ### end Alembic commands ###
