"""
Kalori ve besin değerleri veritabanı (Food-101 sınıfları + Türkçe karşılıklar)
Kaynak: USDA FoodData Central ortalama değerleri (kcal/100g)
"""

FOOD_CALORIE_DB = {
    "apple_pie":              {"tr": "Elmalı Turta",        "kcal": 237, "protein": 2.1, "fat": 11, "carbs": 34},
    "baby_back_ribs":         {"tr": "Izgara Kaburga",      "kcal": 296, "protein": 23,  "fat": 22, "carbs": 0},
    "baklava":                {"tr": "Baklava",             "kcal": 428, "protein": 6.5, "fat": 23, "carbs": 53},
    "beef_carpaccio":         {"tr": "Dana Carpaccio",      "kcal": 152, "protein": 18,  "fat": 9,  "carbs": 0},
    "beef_tartare":           {"tr": "Dana Tartare",        "kcal": 160, "protein": 19,  "fat": 9,  "carbs": 1},
    "beet_salad":             {"tr": "Pancar Salatası",     "kcal": 75,  "protein": 2,   "fat": 3,  "carbs": 11},
    "beignets":               {"tr": "Lokma / Beignets",    "kcal": 389, "protein": 5,   "fat": 21, "carbs": 46},
    "bibimbap":               {"tr": "Bibimbap",            "kcal": 168, "protein": 10,  "fat": 5,  "carbs": 22},
    "bread_pudding":          {"tr": "Ekmek Pudingi",       "kcal": 218, "protein": 6,   "fat": 7,  "carbs": 33},
    "breakfast_burrito":      {"tr": "Kahvaltı Burrito",    "kcal": 202, "protein": 9,   "fat": 8,  "carbs": 24},
    "bruschetta":             {"tr": "Bruschetta",          "kcal": 197, "protein": 5,   "fat": 8,  "carbs": 27},
    "caesar_salad":           {"tr": "Sezar Salatası",      "kcal": 190, "protein": 5,   "fat": 16, "carbs": 7},
    "cannoli":                {"tr": "Cannoli",             "kcal": 329, "protein": 7,   "fat": 18, "carbs": 35},
    "caprese_salad":          {"tr": "Caprese Salatası",    "kcal": 143, "protein": 8,   "fat": 11, "carbs": 4},
    "carrot_cake":            {"tr": "Havuçlu Kek",         "kcal": 415, "protein": 4,   "fat": 20, "carbs": 55},
    "ceviche":                {"tr": "Ceviche",             "kcal": 96,  "protein": 13,  "fat": 2,  "carbs": 7},
    "cheesecake":             {"tr": "Cheesecake",          "kcal": 321, "protein": 5,   "fat": 22, "carbs": 26},
    "cheese_plate":           {"tr": "Peynir Tabağı",       "kcal": 370, "protein": 23,  "fat": 30, "carbs": 2},
    "chicken_curry":          {"tr": "Tavuk Köri",          "kcal": 185, "protein": 17,  "fat": 10, "carbs": 8},
    "chicken_quesadilla":     {"tr": "Tavuklu Quesadilla",  "kcal": 255, "protein": 16,  "fat": 12, "carbs": 21},
    "chicken_wings":          {"tr": "Tavuk Kanatları",     "kcal": 290, "protein": 27,  "fat": 19, "carbs": 0},
    "chocolate_cake":         {"tr": "Çikolatalı Kek",      "kcal": 371, "protein": 4,   "fat": 18, "carbs": 50},
    "chocolate_mousse":       {"tr": "Çikolatalı Mus",      "kcal": 227, "protein": 4,   "fat": 17, "carbs": 16},
    "churros":                {"tr": "Churros",             "kcal": 403, "protein": 5,   "fat": 19, "carbs": 53},
    "clam_chowder":           {"tr": "Deniztaşı Çorbası",   "kcal": 151, "protein": 5,   "fat": 8,  "carbs": 16},
    "club_sandwich":          {"tr": "Kulüp Sandviç",       "kcal": 265, "protein": 16,  "fat": 11, "carbs": 25},
    "crab_cakes":             {"tr": "Yengeç Keki",         "kcal": 190, "protein": 14,  "fat": 11, "carbs": 10},
    "creme_brulee":           {"tr": "Crème Brûlée",        "kcal": 216, "protein": 3,   "fat": 15, "carbs": 18},
    "croque_madame":          {"tr": "Croque Madame",       "kcal": 285, "protein": 14,  "fat": 17, "carbs": 19},
    "cup_cakes":              {"tr": "Cupcake",             "kcal": 346, "protein": 3,   "fat": 15, "carbs": 50},
    "deviled_eggs":           {"tr": "Dolgulu Yumurta",     "kcal": 143, "protein": 7,   "fat": 12, "carbs": 1},
    "donuts":                 {"tr": "Donut",               "kcal": 452, "protein": 5,   "fat": 25, "carbs": 51},
    "dumplings":              {"tr": "Mantı / Dumpling",    "kcal": 148, "protein": 7,   "fat": 4,  "carbs": 22},
    "edamame":                {"tr": "Edamame",             "kcal": 121, "protein": 11,  "fat": 5,  "carbs": 10},
    "eggs_benedict":          {"tr": "Eggs Benedict",       "kcal": 290, "protein": 15,  "fat": 20, "carbs": 14},
    "escargots":              {"tr": "Salyangoz",           "kcal": 116, "protein": 16,  "fat": 4,  "carbs": 2},
    "falafel":                {"tr": "Falafel",             "kcal": 333, "protein": 13,  "fat": 18, "carbs": 32},
    "filet_mignon":           {"tr": "Fileto Mignon",       "kcal": 194, "protein": 26,  "fat": 10, "carbs": 0},
    "fish_and_chips":         {"tr": "Balık & Cips",        "kcal": 297, "protein": 13,  "fat": 14, "carbs": 32},
    "foie_gras":              {"tr": "Foie Gras",           "kcal": 462, "protein": 11,  "fat": 44, "carbs": 5},
    "french_fries":           {"tr": "Patates Kızartması",  "kcal": 312, "protein": 3,   "fat": 15, "carbs": 41},
    "french_onion_soup":      {"tr": "Fransız Soğan Çorbası","kcal": 88, "protein": 4,   "fat": 4,  "carbs": 10},
    "french_toast":           {"tr": "Fransız Tostu",       "kcal": 228, "protein": 9,   "fat": 9,  "carbs": 29},
    "fried_calamari":         {"tr": "Kalamar Tava",        "kcal": 260, "protein": 14,  "fat": 14, "carbs": 22},
    "fried_rice":             {"tr": "Kızarmış Pilav",      "kcal": 183, "protein": 5,   "fat": 5,  "carbs": 30},
    "frozen_yogurt":          {"tr": "Frozen Yoğurt",       "kcal": 127, "protein": 3,   "fat": 2,  "carbs": 25},
    "garlic_bread":           {"tr": "Sarımsaklı Ekmek",    "kcal": 350, "protein": 7,   "fat": 17, "carbs": 43},
    "gnocchi":                {"tr": "Gnocchi",             "kcal": 155, "protein": 4,   "fat": 1,  "carbs": 33},
    "greek_salad":            {"tr": "Yunan Salatası",      "kcal": 95,  "protein": 3,   "fat": 7,  "carbs": 6},
    "grilled_cheese_sandwich":{"tr": "Izgara Peynirli Sandviç","kcal": 337,"protein": 12,"fat": 19, "carbs": 31},
    "grilled_salmon":         {"tr": "Izgara Somon",        "kcal": 208, "protein": 28,  "fat": 10, "carbs": 0},
    "guacamole":              {"tr": "Guacamole",           "kcal": 150, "protein": 2,   "fat": 13, "carbs": 9},
    "gyoza":                  {"tr": "Gyoza",               "kcal": 175, "protein": 8,   "fat": 7,  "carbs": 20},
    "hamburger":              {"tr": "Hamburger",           "kcal": 294, "protein": 17,  "fat": 14, "carbs": 24},
    "hot_and_sour_soup":      {"tr": "Ekşi Acı Çorba",     "kcal": 57,  "protein": 4,   "fat": 1,  "carbs": 8},
    "hot_dog":                {"tr": "Hot Dog",             "kcal": 290, "protein": 10,  "fat": 17, "carbs": 23},
    "huevos_rancheros":       {"tr": "Huevos Rancheros",    "kcal": 178, "protein": 9,   "fat": 9,  "carbs": 16},
    "hummus":                 {"tr": "Humus",               "kcal": 166, "protein": 8,   "fat": 10, "carbs": 14},
    "ice_cream":              {"tr": "Dondurma",            "kcal": 207, "protein": 3,   "fat": 11, "carbs": 24},
    "lasagna":                {"tr": "Lazanya",             "kcal": 166, "protein": 10,  "fat": 7,  "carbs": 16},
    "lobster_bisque":         {"tr": "Istakoz Çorbası",     "kcal": 180, "protein": 8,   "fat": 12, "carbs": 11},
    "lobster_roll_sandwich":  {"tr": "Istakoz Sandviç",     "kcal": 267, "protein": 18,  "fat": 10, "carbs": 27},
    "macaroni_and_cheese":    {"tr": "Makarna & Peynir",    "kcal": 164, "protein": 7,   "fat": 7,  "carbs": 20},
    "macarons":               {"tr": "Macaron",             "kcal": 413, "protein": 5,   "fat": 16, "carbs": 62},
    "miso_soup":              {"tr": "Miso Çorbası",        "kcal": 40,  "protein": 3,   "fat": 1,  "carbs": 5},
    "mussels":                {"tr": "Midye",               "kcal": 172, "protein": 24,  "fat": 5,  "carbs": 7},
    "nachos":                 {"tr": "Nachos",              "kcal": 346, "protein": 9,   "fat": 19, "carbs": 36},
    "omelette":               {"tr": "Omlet",               "kcal": 154, "protein": 11,  "fat": 12, "carbs": 1},
    "onion_rings":            {"tr": "Soğan Halkası",       "kcal": 360, "protein": 5,   "fat": 16, "carbs": 47},
    "oysters":                {"tr": "İstiridye",           "kcal": 68,  "protein": 7,   "fat": 2,  "carbs": 4},
    "pad_thai":               {"tr": "Pad Thai",            "kcal": 168, "protein": 10,  "fat": 5,  "carbs": 23},
    "paella":                 {"tr": "Paella",              "kcal": 172, "protein": 12,  "fat": 5,  "carbs": 20},
    "pancakes":               {"tr": "Pancake",             "kcal": 227, "protein": 6,   "fat": 7,  "carbs": 36},
    "panna_cotta":            {"tr": "Panna Cotta",         "kcal": 244, "protein": 3,   "fat": 18, "carbs": 19},
    "peking_duck":            {"tr": "Pekin Ördeği",        "kcal": 339, "protein": 19,  "fat": 28, "carbs": 0},
    "pho":                    {"tr": "Pho Çorbası",         "kcal": 101, "protein": 7,   "fat": 2,  "carbs": 14},
    "pizza":                  {"tr": "Pizza",               "kcal": 266, "protein": 11,  "fat": 10, "carbs": 33},
    "pork_chop":              {"tr": "Domuz Pirzolası",     "kcal": 231, "protein": 28,  "fat": 13, "carbs": 0},
    "poutine":                {"tr": "Poutine",             "kcal": 260, "protein": 8,   "fat": 13, "carbs": 28},
    "prime_rib":              {"tr": "Prime Rib",           "kcal": 303, "protein": 26,  "fat": 22, "carbs": 0},
    "pulled_pork_sandwich":   {"tr": "Pulled Pork Sandviç", "kcal": 272, "protein": 18,  "fat": 10, "carbs": 26},
    "ramen":                  {"tr": "Ramen",               "kcal": 138, "protein": 7,   "fat": 4,  "carbs": 19},
    "ravioli":                {"tr": "Ravioli",             "kcal": 214, "protein": 10,  "fat": 7,  "carbs": 27},
    "red_velvet_cake":        {"tr": "Kırmızı Kadife Kek",  "kcal": 389, "protein": 5,   "fat": 18, "carbs": 53},
    "risotto":                {"tr": "Risotto",             "kcal": 166, "protein": 5,   "fat": 5,  "carbs": 26},
    "samosa":                 {"tr": "Samosa",              "kcal": 262, "protein": 5,   "fat": 14, "carbs": 30},
    "sashimi":                {"tr": "Sashimi",             "kcal": 127, "protein": 20,  "fat": 5,  "carbs": 0},
    "scallops":               {"tr": "Deniz Tarağı",        "kcal": 111, "protein": 20,  "fat": 1,  "carbs": 5},
    "seaweed_salad":          {"tr": "Deniz Yosunu Salatası","kcal": 45, "protein": 2,   "fat": 0,  "carbs": 8},
    "shrimp_and_grits":       {"tr": "Karidesli Grits",     "kcal": 213, "protein": 14,  "fat": 8,  "carbs": 21},
    "spaghetti_bolognese":    {"tr": "Bolonez Makarna",     "kcal": 198, "protein": 11,  "fat": 7,  "carbs": 24},
    "spaghetti_carbonara":    {"tr": "Karbonara Makarna",   "kcal": 261, "protein": 12,  "fat": 12, "carbs": 27},
    "spring_rolls":           {"tr": "Bahar Rulo",          "kcal": 97,  "protein": 3,   "fat": 3,  "carbs": 15},
    "steak":                  {"tr": "Biftek",              "kcal": 271, "protein": 26,  "fat": 18, "carbs": 0},
    "strawberry_shortcake":   {"tr": "Çilekli Kek",         "kcal": 301, "protein": 4,   "fat": 12, "carbs": 44},
    "sushi":                  {"tr": "Sushi",               "kcal": 143, "protein": 7,   "fat": 2,  "carbs": 27},
    "tacos":                  {"tr": "Taco",                "kcal": 218, "protein": 11,  "fat": 9,  "carbs": 23},
    "takoyaki":               {"tr": "Takoyaki",            "kcal": 200, "protein": 8,   "fat": 9,  "carbs": 22},
    "tiramisu":               {"tr": "Tiramisu",            "kcal": 283, "protein": 5,   "fat": 18, "carbs": 26},
    "tuna_tartare":           {"tr": "Ton Balığı Tartare",  "kcal": 130, "protein": 22,  "fat": 4,  "carbs": 1},
    "waffles":                {"tr": "Waffle",              "kcal": 291, "protein": 7,   "fat": 12, "carbs": 40},
}


def get_food_info(food_label: str) -> dict:
    """Food-101 etiketini kalori + Türkçe bilgiye çevirir."""
    info = FOOD_CALORIE_DB.get(food_label)
    if info:
        return {
            "food_name": food_label,
            "food_name_tr": info["tr"],
            "calories_per_100g": info["kcal"],
            "protein_per_100g": info["protein"],
            "fat_per_100g": info["fat"],
            "carbs_per_100g": info["carbs"],
            "found": True,
        }
    return {
        "food_name": food_label,
        "food_name_tr": food_label.replace("_", " ").title(),
        "calories_per_100g": None,
        "protein_per_100g": None,
        "fat_per_100g": None,
        "carbs_per_100g": None,
        "found": False,
    }
